# Generated by Django 5.2.15 on 2026-07-11 09:51

from django.db import migrations, models

import apps.homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkattachment',
            name='file',
            field=models.FileField(upload_to=apps.homework.models.homework_file_path),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to=apps.homework.models.submission_file_path),
        ),
    ]
