# Generated by Django 5.2.15 on 2026-07-02 10:32

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_subject_order'),
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceSession',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_bs', models.CharField(db_index=True, max_length=10)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.staff')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendanceRecord',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_bs', models.CharField(db_index=True, max_length=10)),
                ('present', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=50)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.staff')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('present', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.classattendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='people.student')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='classattendancesession',
            constraint=models.UniqueConstraint(fields=('school', 'class_info', 'date_bs'), name='uniq_class_session'),
        ),
        migrations.AddConstraint(
            model_name='staffattendancerecord',
            constraint=models.UniqueConstraint(fields=('staff', 'date_bs'), name='uniq_staff_attd'),
        ),
        migrations.AddConstraint(
            model_name='studentattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_student_attd'),
        ),
    ]
