# Generated by Django 5.2.15 on 2026-07-03 02:30

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('natural_side', models.CharField(choices=[('dr', 'Dr.'), ('cr', 'Cr.')], max_length=2)),
                ('category', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity')], max_length=10)),
                ('cash_flow', models.CharField(blank=True, choices=[('operating', 'Operating'), ('investing', 'Investing'), ('financing', 'Financing')], default='', max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('start_date_bs', models.CharField(max_length=10)),
                ('end_date_bs', models.CharField(max_length=10)),
                ('closed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_years', to='accounting.fiscalyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('contact', models.CharField(blank=True, default='', max_length=15)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgergroup')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('side', models.CharField(choices=[('dr', 'Dr.'), ('cr', 'Cr.')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.fiscalyear')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.ledgeraccount')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voucher_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('journal', 'Journal'), ('contra', 'Contra')], db_index=True, max_length=8)),
                ('serial', models.PositiveIntegerField()),
                ('date_bs', models.CharField(max_length=10)),
                ('mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank')], default='', max_length=4)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('needs_review', models.BooleanField(default=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('cash_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.fiscalyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('side', models.CharField(choices=[('dr', 'Dr.'), ('cr', 'Cr.')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucher')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VoucherSerialCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('journal', 'Journal'), ('contra', 'Contra')], max_length=8)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.fiscalyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_fiscal_year_name'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['school', 'group'], name='accounting__school__cb1355_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(fields=('ledger', 'fiscal_year'), name='uniq_opening_balance'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['school', 'fiscal_year', 'date_bs'], name='accounting__school__804f0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('school', 'fiscal_year', 'voucher_type', 'serial'), name='uniq_voucher_serial'),
        ),
        migrations.AddConstraint(
            model_name='voucherserialcounter',
            constraint=models.UniqueConstraint(fields=('school', 'fiscal_year', 'voucher_type'), name='uniq_voucher_serial_counter'),
        ),
    ]
