# Generated by Django 5.2.15 on 2026-07-03 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_groups_balance_trigger'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('voucher_type', 'legacy_id'), name='uniq_voucher_legacy_id'),
        ),
    ]
