# Generated by Django 5.2.15 on 2026-07-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('legacy_table', models.CharField(max_length=80)),
                ('legacy_id', models.BigIntegerField()),
                ('new_table', models.CharField(max_length=80)),
                ('new_id', models.UUIDField()),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['new_table', 'new_id'], name='core_legacy_new_tab_b2a0d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('legacy_table', 'legacy_id'), name='uniq_legacy_row')],
            },
        ),
    ]
