# Generated by Django 5.2.15 on 2026-07-02 02:06

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('soft_delete', 'Soft delete'), ('login', 'Login'), ('read_sensitive', 'Sensitive read')], max_length=16)),
                ('object_table', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=40)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
