# Generated by Django 5.2.15 on 2026-07-02 02:32

from django.db import migrations

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='id',
            field=apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
