# Generated by Django 5.2.15 on 2026-07-04 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
