# Generated by Django 5.2.15 on 2026-07-17 16:10

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_serials_key_on_fiscal_year'),
        ('tenants', '0003_schoolbranding_print_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='edu_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='edu_fee_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='edu_fee_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='EducationFeeLevel',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('education_level', models.CharField(choices=[('montessori', 'Montessori'), ('school', 'School'), ('school_govt', 'School (GOVT.)'), ('pre_diploma', 'Pre-diploma'), ('diploma', 'Diploma'), ('highschool', 'High school'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_fee_levels', to='tenants.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'education_level'), name='uniq_education_fee_level')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
