# Generated by Django 5.2.15 on 2026-07-03 01:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_subject_order'),
        ('billing', '0001_initial'),
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAccrual',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_bs', models.CharField(max_length=10)),
                ('months', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('billing_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.billingyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_accruals', to='people.staff')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAccrualLine',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('earning_type', models.CharField(choices=[('salary', 'Basic salary'), ('grade', 'Grade'), ('allowance', 'Allowance'), ('extra', 'Extra')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accrual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salaryaccrual')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('date_bs', models.CharField(max_length=10)),
                ('payment_month', models.PositiveSmallIntegerField(default=0)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], default='cash', max_length=8)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('billing_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.billingyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='people.staff')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPaymentLine',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('earning_type', models.CharField(choices=[('salary', 'Basic salary'), ('grade', 'Grade'), ('allowance', 'Allowance'), ('extra', 'Extra')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tds_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarypayment')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from_bs', models.CharField(blank=True, default='', max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pan_no', models.CharField(blank=True, default='', max_length=20)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='people.staff')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSerialCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('billing_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.billingyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'billing_year'), name='uniq_payroll_serial_counter')],
            },
        ),
        migrations.AddIndex(
            model_name='salaryaccrual',
            index=models.Index(fields=['school', 'staff'], name='payroll_sal_school__e2722e_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['school', 'staff'], name='payroll_sal_school__6afd11_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(condition=models.Q(('serial__isnull', False)), fields=('school', 'billing_year', 'serial'), name='uniq_salary_payment_serial'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.CheckConstraint(condition=models.Q(('net_paid', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross'), '-', models.F('tds_amount')), '-', models.F('pf_amount')), '-', models.F('insurance_amount')))), name='salary_payment_net_identity'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('staff', 'effective_from_bs'), name='uniq_salary_structure_version'),
        ),
    ]
