# Generated by Django 5.2.15 on 2026-07-02 10:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_subject_order'),
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCertificate',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_no', models.CharField(max_length=40)),
                ('data', models.JSONField()),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='people.student')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('inclusion_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('include_attendance', models.BooleanField(default=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('number', 'Number system'), ('grading', 'Grading system'), ('division', 'Division')], max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(max_length=60)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='examinations.gradingscheme')),
            ],
            options={
                'ordering': ['min_score'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResultSheet',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('full_marks_theory', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_marks_theory', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('full_marks_practical', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_marks_practical', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attendance_days', models.IntegerField(blank=True, null=True)),
                ('published_date_bs', models.CharField(blank=True, default='', max_length=10)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_sheets', to='academics.subject')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectResult',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('theory', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('practical', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('inclusion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attendance_days', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('position_in_section', models.IntegerField(blank=True, null=True)),
                ('position_in_class', models.IntegerField(blank=True, null=True)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='people.student')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.subjectresultsheet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityGrade',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.CharField(max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='examinations.activitydefinition')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='people.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='examinations.exam')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('exam', 'student', 'activity'), name='uniq_activity_grade')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamScheduleEntry',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_date_bs', models.CharField(max_length=10)),
                ('start_time', models.CharField(blank=True, default='', max_length=10)),
                ('end_time', models.CharField(blank=True, default='', max_length=10)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'Exam schedule entries',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('exam', 'class_info', 'subject'), name='uniq_schedule_sitting')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='gradingscheme',
            constraint=models.UniqueConstraint(fields=('school', 'type'), name='uniq_grading_scheme'),
        ),
        migrations.AddConstraint(
            model_name='subjectresultsheet',
            constraint=models.UniqueConstraint(fields=('exam', 'class_info', 'subject'), name='uniq_result_sheet'),
        ),
        migrations.AddIndex(
            model_name='studentsubjectresult',
            index=models.Index(fields=['school', 'student'], name='examination_school__2f4dad_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectresult',
            constraint=models.UniqueConstraint(fields=('sheet', 'student'), name='uniq_student_mark'),
        ),
    ]
