# Generated by Django 5.2.15 on 2026-07-11 01:55

import apps.core.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subject_order'),
        ('billing', '0002_serials_key_on_fiscal_year'),
        ('examinations', '0001_initial'),
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlanRoom',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('benches', models.PositiveIntegerField(default=1)),
                ('seats_per_bench', models.PositiveIntegerField(default=2)),
                ('order_by', models.CharField(choices=[('roll', 'Roll no'), ('symbol', 'Symbol no'), ('name', 'Name (alphabetical)'), ('regd', 'Registration no')], default='roll', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_plan_rooms', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSerialCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('billing_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.billingyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'billing_year'), name='uniq_certificate_serial_counter')],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bench_no', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='examinations.seatplanroom')),
            ],
            options={
                'ordering': ['sequence'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('room', 'bench_no', 'column'), name='uniq_room_seat'), models.UniqueConstraint(fields=('room', 'student'), name='uniq_room_student')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SeatPlanRoomClass',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('column', models.PositiveIntegerField(default=1)),
                ('order_by', models.CharField(blank=True, choices=[('roll', 'Roll no'), ('symbol', 'Symbol no'), ('name', 'Name (alphabetical)'), ('regd', 'Registration no')], default='', max_length=8)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.classinfo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_classes', to='examinations.seatplanroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'Seat plan room classes',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('room', 'column'), name='uniq_room_column')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
