# Generated by Django 5.2.15 on 2026-07-02 10:32

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('alias', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware', models.CharField(blank=True, default='', max_length=64)),
                ('push_version', models.CharField(blank=True, default='', max_length=16)),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
                ('push_comm_key', models.CharField(blank=True, default='', max_length=64)),
                ('timezone_min', models.IntegerField(default=345)),
                ('real_time', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('connecting', 'Connecting'), ('online', 'Online')], default='registered', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('attlog_stamp', models.CharField(default='None', max_length=32)),
                ('operlog_stamp', models.CharField(default='None', max_length=32)),
                ('photo_stamp', models.CharField(default='None', max_length=32)),
                ('user_count', models.IntegerField(default=0)),
                ('fp_count', models.IntegerField(default=0)),
                ('face_count', models.IntegerField(default=0)),
                ('trans_count', models.IntegerField(default=0)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pin', models.CharField(max_length=24)),
                ('privilege', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, default='', max_length=16)),
                ('card', models.CharField(blank=True, default='', max_length=32)),
                ('group_id', models.IntegerField(default=1)),
                ('tz_str', models.CharField(blank=True, default='', max_length=32)),
                ('verify', models.IntegerField(default=-1)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='devices.device')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_users', to='people.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_users', to='people.student')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(default=0)),
                ('verify', models.IntegerField(default=0)),
                ('workcode', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='devices.deviceuser')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmd_id', models.CharField(max_length=16, unique=True)),
                ('cmd_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('return_info', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status'], name='devices_dev_device__0a9c1c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceuser',
            constraint=models.UniqueConstraint(fields=('device', 'pin'), name='uniq_device_pin'),
        ),
        migrations.AddConstraint(
            model_name='punchlog',
            constraint=models.UniqueConstraint(fields=('user', 'punch_time', 'status', 'verify'), name='uniq_punch'),
        ),
    ]
