# Generated by Django 5.2.15 on 2026-07-02 02:28

import django.db.models.manager
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('start_date_bs', models.CharField(max_length=10)),
                ('end_date_bs', models.CharField(max_length=10)),
                ('closed', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('education_level', models.CharField(choices=[('montessori', 'Montessori'), ('school', 'School'), ('school_govt', 'School (GOVT.)'), ('pre_diploma', 'Pre-diploma'), ('diploma', 'Diploma'), ('highschool', 'High school'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('play_group', 'Play group'), ('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six'), ('seven', 'Seven'), ('eight', 'Eight'), ('nine', 'Nine'), ('ten', 'Ten'), ('eleven', 'Eleven'), ('twelve', 'Twelve')], default='', max_length=12)),
                ('faculty', models.CharField(blank=True, choices=[('science', 'Science'), ('management', 'Management'), ('education', 'Education'), ('arts', 'Arts'), ('humanities', 'Humanities'), ('law', 'Law')], default='', max_length=12)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Class infos',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('education_level', models.CharField(choices=[('montessori', 'Montessori'), ('school', 'School'), ('school_govt', 'School (GOVT.)'), ('pre_diploma', 'Pre-diploma'), ('diploma', 'Diploma'), ('highschool', 'High school'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentYearPointer',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('type', models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional')], default='compulsory', max_length=10)),
                ('credit_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name_practical', models.CharField(blank=True, default='', max_length=50)),
                ('code_practical', models.CharField(blank=True, default='', max_length=10)),
                ('credit_hours_practical', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
