# Generated by Django 5.2.15 on 2026-07-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.course'),
        ),
        migrations.AddField(
            model_name='currentyearpointer',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_pointers', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='currentyearpointer',
            name='previous_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='currentyearpointer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.classinfo'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_ay_per_school'),
        ),
        migrations.AddConstraint(
            model_name='currentyearpointer',
            constraint=models.UniqueConstraint(fields=('school', 'key'), name='uniq_year_pointer_key'),
        ),
        migrations.AddConstraint(
            model_name='classinfo',
            constraint=models.UniqueConstraint(fields=('school', 'education_level', 'grade', 'faculty', 'course', 'section', 'year', 'semester', 'academic_year'), name='uniq_class_tuple', nulls_distinct=False),
        ),
    ]
