# Generated by Django 5.2.15 on 2026-07-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='uniq_ay_per_school',
        ),
    ]
