# Generated by Django 5.2.15 on 2026-07-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicyear_id_alter_classinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
