# Generated by Django 5.2.15 on 2026-07-17 16:33

import apps.core.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subject_order'),
        ('tenants', '0003_schoolbranding_print_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', apps.core.models.UUIDv7Field(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=9)),
                ('current_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('graduated', models.BooleanField(default=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='classinfo',
            name='uniq_class_tuple',
        ),
        migrations.AddField(
            model_name='course',
            name='total_semesters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.batch'),
        ),
        migrations.AddConstraint(
            model_name='classinfo',
            constraint=models.UniqueConstraint(fields=('school', 'education_level', 'grade', 'faculty', 'course', 'section', 'year', 'semester', 'academic_year', 'batch'), name='uniq_class_tuple', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('school', 'course', 'year'), name='uniq_batch_intake', nulls_distinct=False),
        ),
    ]
