# Generated by Django 5.2.15 on 2026-07-02 02:06

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
                ('ceo', models.CharField(blank=True, default='', max_length=60)),
                ('estd_date_bs', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pan_no', models.CharField(blank=True, default='', max_length=20)),
                ('estd_date_bs', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('is_test', models.BooleanField(default=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('admin_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_admin_of', to=settings.AUTH_USER_MODEL)),
                ('foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='tenants.foundation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slogan', models.CharField(blank=True, default='', max_length=120)),
                ('about_us', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logo/')),
                ('award_logo', models.ImageField(blank=True, null=True, upload_to='branding/award/')),
                ('principal_sign', models.ImageField(blank=True, null=True, upload_to='branding/sign/')),
                ('exam_coordinator_sign', models.ImageField(blank=True, null=True, upload_to='branding/sign/')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'School branding',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uses_sms', models.BooleanField(default=False)),
                ('uses_mobile_app', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=40)),
                ('hidden_education_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('time_set_required', models.BooleanField(default=False)),
                ('attendance_in_time', models.TimeField(blank=True, null=True)),
                ('attendance_out_time', models.TimeField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'School settings',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
                ('foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='tenants.foundation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
