# Generated by Django 5.2.15 on 2026-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_foundation_id_alter_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranding',
            name='print_design',
            field=models.CharField(choices=[('classic', 'Classic (traditional bordered)'), ('elegant', 'Elegant (minimal, airy)'), ('formal', 'Formal (national-exam grid)'), ('compact', 'Compact (dense, many prints)')], default='classic', max_length=12),
        ),
    ]
