# Generated by Django 5.2.15 on 2026-07-02 02:28

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('contact', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=40)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date_bs', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=8)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed_out', 'Passed out'), ('dropped_out', 'Dropped out')], default='running', max_length=12)),
                ('roll_no', models.CharField(blank=True, default='', max_length=15)),
                ('symbol_no', models.CharField(blank=True, default='', max_length=15)),
                ('regd_no', models.CharField(blank=True, default='', max_length=15)),
                ('emis', models.CharField(blank=True, default='', max_length=50)),
                ('rfid_card', models.CharField(blank=True, default='', max_length=32)),
                ('previous_school', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=30)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.classinfo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=10)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='people.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='people.student')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('employed', 'Employed'), ('departed', 'Departed'), ('retired', 'Retired'), ('on_leave', 'On leave')], default='employed', max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='', max_length=8)),
                ('birth_date_bs', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('primary_contact', models.CharField(max_length=15)),
                ('secondary_contact', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('qualification', models.CharField(blank=True, default='', max_length=100)),
                ('joined_date_bs', models.CharField(blank=True, default='', max_length=10)),
                ('rfid_card', models.CharField(blank=True, default='', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('secondary_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='people.staffrole')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['school', 'status'], name='people_staf_school__7c6a17_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='people_stud_school__3d02ea_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_info'], name='people_stud_school__9bbfdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian', 'relation'), name='uniq_student_guardian'),
        ),
    ]
