# Generated by Django 5.2.15 on 2026-07-11 09:48

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_guardian_id_alter_staff_id_alter_staffrole_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.people.models.staff_photo_path),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.people.models.student_photo_path),
        ),
    ]
