# Generated by Django 5.2.15 on 2026-07-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_batch_remove_classinfo_uniq_class_tuple_and_more'),
        ('people', '0003_staff_photo_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.batch'),
        ),
    ]
