# Generated by Django 5.2.15 on 2026-07-02 02:28

import django.core.validators
from django.db import migrations, models

import apps.core.models
import apps.identity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', apps.core.models.UUIDv7Field(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(4)])),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'School Admin'), ('staff', 'Staff'), ('student', 'Student'), ('guardian', 'Guardian')], db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_table', models.CharField(blank=True, default='', max_length=40)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='identity_ac_usernam_727fca_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'username'), name='uniq_role_username')],
            },
            managers=[
                ('objects', apps.identity.models.AccountManager()),
            ],
        ),
    ]
