# Generated by Django 5.2.15 on 2026-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
    ]
